### ISSUE TITLE
Expand the Contribute Section of the Readme to talk about Builds and Tests

### ISSUE THREAD

**Issue by frastlin** [rserota/wad#124]
I would like a brief section about how the folders are layed out, I always forget, and it takes me a little while to figure out how to run the tests and do the builds. Also, it would be really useful if webpack watch mode and webpack-dev-server could serve the test folder.
https://webpack.js.org/guides/development/

**Comment by rserota** [comment]
There should definitely be a more descriptive "How to contribute" section, but before I do that I want to restructure the project to make it easier to contribute to. 

I'll take a look at webpack watch mode and webpack dev server.

**Comment by frastlin** [comment]
If you split the project into modules, then that will make it easier to understand. If there was the main Wad module, then it would be easier to figure out where to put new features. But until then, I think just doing the description of the layout would be helpful. For example, what is tests/5?

**Comment by rserota** [comment]
Right, I wanted to split the project into modules to make it all easier to understand. I know the main `wad.js` file had gotten too large a while ago. 
About the tests, I wanted to make sure that Wad.js works when imported as an ES6 module, and also works when it's just linked in a script tag, as you would do in ES5, so that's why there's basically two sets of similar tests. The tests could definitely be refactored to be less redundant. Or maybe at this point, it's just not as necessary to maintain both versions of the tests.

**Comment by rserota** [comment]
The project has been restructured, and the readme has been rewritten. There's probably still room for improvement, but it should be a lot easier now for other people to understand the code and contribute to the project.

**Comment by frastlin** [comment]
Looks great, thank you!
