### ISSUE TITLE
Determine if currently playing

### ISSUE THREAD

**Issue by richtier** [rserota/wad#96]
I would like to determine when wad has finished playing.

I have a play queue - so when one has finished the other can start.

I have a` setInterval` that simply checks `isPlaying`.

I've checked the code and docs and cannot see a callback or state to check.

**Comment by rserota** [comment]
The `play()` method of a wad object returns a promise, which resolves when that wad finishes playing. This makes it pretty easy to play a queue of wads in sequence, using async/await, or other promise methods. This is briefly mentioned in the docs, near https://github.com/rserota/wad#play. 
Does that help?

**Comment by richtier** [comment]
the promise seems to resolve immediately. I have:

```
    // samples is mp3 data provided by a websocket
    var blob = new Blob([samples]);
    var src = URL.createObjectURL(blob)
    var wadSound = new Wad({source: src});
    wadSound.then(function(){
        console.log('finished')
    })
    console.log('started')
  }
```

with a 5 second mp3 the console shows `started` and `finished` immediately

**Comment by rserota** [comment]
Hmm.... so, for one thing, the promise is returned from the `play()` method, not the constructor, like you've written above. I'm assuming that this error is only in the snippet above, and not in your actual code. 
Another potential issue is that because you're instantiating a wad object in a somewhat unusual way, it's possible that the constructor function doesn't properly detect the length of the audio. As a possible workaround, if you already know how long the audio clips are, you can manually assign the duration to the wad.
```
wadSound.defaultEnv.hold = 2.5 
wadSound.play().then(function(){
    console.log('hello') // this log will appear 2.5 seconds after calling play()
})
```

**Comment by richtier** [comment]
> assuming this error is only in the snippet above

Correct :)

I think Alexa returns the length of the audio in milliseconds so I can set the hold time. Thanks.
